name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -S . -B build
          cmake --build build/ --config Release -j
          mkdir lib/
          mv build/Release/nbsparser.lib lib/nbsparser.lib

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: nbsparser-win-x64
          path: |
            ./include
            ./lib

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          sudo apt install cmake -y
          cmake -S . -B build
          cmake --build build/ --config Release -j
          mkdir lib/
          mv build/libnbsparser.a lib/libnbsparser.a

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: nbsparser-linux-x64
          path: |
            ./include
            ./lib
